version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: qrcodecheckin-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: qrcodecheckin-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  springboot:
    build: .
    container_name: qrcodecheckin-backend
    restart: always
    depends_on:
      - mysql
    environment:
      TZ: Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CORS_ALLOWED_ORIGINS: http://localhost:5000
    ports:
      - "8080:8080"
    networks:
      - app-network

  react:
    image: qrcodecheckin-react
    container_name: qrcodecheckin-frontend
    depends_on:
      - springboot
    environment:
      TZ: Asia/Ho_Chi_Minh
      VITE_BASE_API_URL: http://localhost:8080/api/
    ports:
      - "5000:5000"
    networks:
      - app-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: qrcodecheckin-ngrok
    ports:
      - "4040:4040"
    command:
      - "http"
      - "springboot:8080"
    environment:
      - NGROK_AUTHTOKEN=2tQdy450dZJZ9NwxE6BFA7IKbPH_3mkiXEZWKhZhPYszaVSHq
    networks:
      - app-network
    depends_on:
      - springboot

networks:
  app-network:
    driver: bridge